#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Мастер настройки ORBITA — docs/SETUP.md, шаги 1–3 и проверка.
#
# Запуск из корня репозитория в Git Bash:   bash scripts/setup-wizard.sh
#
# Ничего секретного мастер не печатает и не пишет в файлы: значения уходят прямо в GitHub
# Secrets (`gh secret set`) и в переменные проекта Vercel (`vercel env add`). Токены входа,
# которые нужно сохранить себе, кладутся в буфер обмена — вставьте их в менеджер паролей.

TOTAL_STAGES=10

# Значения не пишутся ни в какой файл: подсказки «оставить прежнее» из .env мастеру не нужны,
# а рабочие ключи не должны лежать рядом с кодом публичного репозитория.
ENV_FILE="${HOME}/.orbita-wizard-nothing-is-stored-here"
REPO="${REPO:-yuldoshbek/Project_}"
ENVIRONMENT="production"

# Значения, которые нужны нескольким этапам; живут только в памяти этого запуска.
PRODUCTION_DATABASE_URL=""
PRODUCTION_URL=""
PRODUCTION_API_ORIGIN=""
PRODUCTION_SESSION_SECRET=""
PRODUCTION_JOBS_SECRET=""
VERCEL_TOKEN=""
VERCEL_ORG_ID=""
VERCEL_PROJECT_ID=""

# gen N — случайная строка из N байт в base64url. Не печатается: только в переменную.
gen() {
  python -c "import secrets; print(secrets.token_urlsafe($1))" 2>/dev/null \
    || py -c "import secrets; print(secrets.token_urlsafe($1))" 2>/dev/null \
    || openssl rand -base64 "$1" | tr '+/' '-_' | tr -d '=\n'
}

# to_clipboard VALUE — в буфер обмена, чтобы не показывать на экране.
to_clipboard() {
  if command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  elif command -v pbcopy >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v xclip >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  else return 1; fi
}

# secret_exists NAME [env] — есть ли секрет (значение GitHub не отдаёт, только имя).
secret_exists() {
  local name="$1" env="${2:-}"
  if [[ -n "$env" ]]; then
    gh secret list --repo "$REPO" --env "$env" --json name -q '.[].name' 2>/dev/null | grep -qx "$name"
  else
    gh secret list --repo "$REPO" --json name -q '.[].name' 2>/dev/null | grep -qx "$name"
  fi
}

# put_secret NAME VALUE [env] — секрет репозитория или окружения; значение идёт через stdin.
put_secret() {
  local name="$1" value="$2" env="${3:-}"
  if [[ -z "$value" ]]; then
    SKIPPED+=("секрет $name — значение не введено")
    warn "пропущен $name: значение пустое"
    return
  fi
  local args=(secret set "$name" --repo "$REPO")
  [[ -n "$env" ]] && args+=(--env "$env")
  if printf '%s' "$value" | gh "${args[@]}" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("${env:+$env/}$name")
    printf '  %s✓ записан%s секрет %s%s\n' "$GREEN" "$RESET" "${env:+$env/}" "$name"
  else
    SKIPPED+=("секрет ${env:+$env/}$name — gh отказал")
    warn "не удалось записать $name — проверьте права gh на репозиторий"
  fi
}

# want_secret NAME [env] — спросить значение, только если секрета ещё нет или его меняют.
want_secret() {
  local name="$1" env="${2:-}"
  if secret_exists "$name" "$env"; then
    confirm "Секрет $name уже есть. Заменить?"
  else
    return 0
  fi
}

# vercel_env NAME VALUE — переменная окружения Production в проекте Vercel.
vercel_env() {
  local name="$1" value="$2"
  [[ -n "$value" ]] || { warn "пропущена переменная Vercel $name: значение неизвестно"; return; }
  if [[ -n "$VERCEL_TOKEN" && -n "$VERCEL_ORG_ID" && -n "$VERCEL_PROJECT_ID" ]]; then
    # Есть — заменяем: `env add` отказывает, если переменная уже заведена.
    VERCEL_ORG_ID="$VERCEL_ORG_ID" VERCEL_PROJECT_ID="$VERCEL_PROJECT_ID" \
      npx --yes vercel@latest env rm "$name" production --yes --token="$VERCEL_TOKEN" >/dev/null 2>&1 || true
    if printf '%s' "$value" | VERCEL_ORG_ID="$VERCEL_ORG_ID" VERCEL_PROJECT_ID="$VERCEL_PROJECT_ID" \
      npx --yes vercel@latest env add "$name" production --token="$VERCEL_TOKEN" >/dev/null 2>&1; then
      printf '  %s✓ задана%s переменная Vercel %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  # Без CLI — вручную, значение через буфер обмена, а не на экране.
  warn "Vercel CLI не справился — задайте $name вручную"
  step "Vercel → проект → Settings → Environment Variables → Add → Key: $name, окружение Production"
  if to_clipboard "$value"; then
    say "Значение уже в буфере обмена: вставьте его в поле Value и нажмите Save."
  else
    SKIPPED+=("переменная Vercel $name — буфер обмена недоступен, задайте вручную")
  fi
  pause "Готово? Enter —"
}

banner "ORBITA · настройка рабочего контура"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Проверка инструментов"
say "Мастер пишет ключи прямо в GitHub через gh и в Vercel через npx vercel."
if ! command -v gh >/dev/null 2>&1; then
  warn "Нет GitHub CLI (gh). Установите: https://cli.github.com — и запустите мастер снова."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  say "gh не вошёл в GitHub. Сейчас откроется вход в браузере."
  gh auth login --web --git-protocol https
fi
gh repo view "$REPO" >/dev/null 2>&1 || { warn "Нет доступа к $REPO под этим входом gh."; exit 1; }
say "✓ gh видит репозиторий $REPO"
command -v npx >/dev/null 2>&1 && say "✓ есть npx — переменные Vercel зададим командой" \
  || note "npx нет — переменные Vercel зададим вручную через буфер обмена"
to_clipboard "" && say "✓ буфер обмена доступен" || warn "Буфер обмена недоступен: токены входа придётся сохранить вручную"
pause "Enter — к Neon"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon: проект и ветки базы"
say "Neon — база данных. Регион выбирается один раз и потом не меняется."
open_url "https://console.neon.tech/app/projects"
step "New project → Postgres 16 → регион AWS Europe Central 1 (Frankfurt) — обязательно (ADR-0028)."
step "Имя базы: orbita, роль: orbita."
step "Ветка по умолчанию — переименуйте в production (Branches → … → Rename)."
step "Branches → New branch → имя demo, родитель production — сразу, пока база пустая."
step "Settings → Storage → History retention (Point-in-time restore) → 7 дней."
pause "Сделали проект и ветки production и demo? Enter —"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Neon: ключи"
if want_secret NEON_API_KEY; then
  open_url "https://console.neon.tech/app/settings/api-keys"
  step "Create new API key → имя orbita-github → скопируйте ключ (показывается один раз)."
  ask_secret NEON_API_KEY "Вставьте API-ключ Neon (не отображается):"
  put_secret NEON_API_KEY "$NEON_API_KEY"
fi
if want_secret NEON_PROJECT_ID; then
  step "Проект → Settings → General → Project ID."
  ask NEON_PROJECT_ID "Вставьте Project ID:"
  put_secret NEON_PROJECT_ID "$NEON_PROJECT_ID"
fi
if want_secret PRODUCTION_DATABASE_URL "$ENVIRONMENT"; then
  step "Dashboard → Connect → ветка production → роль orbita → скопируйте строку подключения"
  note "вида postgresql://orbita:…@…neon.tech/orbita?sslmode=require — править её не нужно."
  ask_secret PRODUCTION_DATABASE_URL "Вставьте строку подключения production (не отображается):"
fi
pause "Enter — к Vercel"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel: проект и настройки"
say "Vercel — API. Выкладывает только конвейер, поэтому автосборки выключаем."
open_url "https://vercel.com/new"
step "Import Git Repository → $REPO → Root Directory: backend → Deploy (первая сборка может упасть — это нормально)."
step "Project → Settings → Git → отключите автоматические выкладки (Ignored Build Step: exit 0 или Disconnect)."
step "Project → Settings → Deployment Protection → Vercel Authentication → выключите для Preview."
step "Project → Settings → Domains — запомните рабочий адрес API, например https://orbita-api.vercel.app"
pause "Сделали? Enter —"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel: ключи"
open_url "https://vercel.com/account/tokens"
step "Create Token → имя orbita-github → Scope: ваша команда → скопируйте токен."
ask_secret VERCEL_TOKEN "Вставьте токен Vercel (не отображается):"
want_secret VERCEL_TOKEN && put_secret VERCEL_TOKEN "$VERCEL_TOKEN"
step "Team Settings → General → Team ID (у личного аккаунта — Account Settings → General → Vercel ID)."
ask VERCEL_ORG_ID "Вставьте Team ID (VERCEL_ORG_ID):"
want_secret VERCEL_ORG_ID && put_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
step "Project → Settings → General → Project ID."
ask VERCEL_PROJECT_ID "Вставьте Project ID (VERCEL_PROJECT_ID):"
want_secret VERCEL_PROJECT_ID && put_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
ask PRODUCTION_API_ORIGIN "Рабочий адрес API (https://…vercel.app, без / в конце):"
PRODUCTION_API_ORIGIN="${PRODUCTION_API_ORIGIN%/}"
pause "Enter — к Netlify"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Netlify: сайт и ключи"
say "Netlify — интерфейс. Сборки от репозитория останавливаем: собирает конвейер."
open_url "https://app.netlify.com"
step "Ваш сайт → Site configuration → Build & deploy → Continuous deployment → Stop builds."
step "Site configuration → General → Site details → Site ID — скопируйте."
ask NETLIFY_SITE_ID "Вставьте Site ID:"
want_secret NETLIFY_SITE_ID && put_secret NETLIFY_SITE_ID "$NETLIFY_SITE_ID"
if want_secret NETLIFY_AUTH_TOKEN; then
  open_url "https://app.netlify.com/user/applications#personal-access-tokens"
  step "New access token → имя orbita-github → срок без истечения или год → скопируйте."
  ask_secret NETLIFY_AUTH_TOKEN "Вставьте токен Netlify (не отображается):"
  put_secret NETLIFY_AUTH_TOKEN "$NETLIFY_AUTH_TOKEN"
fi
ask PRODUCTION_URL "Адрес интерфейса (https://….netlify.app или свой домен, без / в конце):"
PRODUCTION_URL="${PRODUCTION_URL%/}"
pause "Enter — к секретам превью"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Секреты превью"
say "Превью каждого PR работает со своими ключами и копией демо-данных."
if want_secret PREVIEW_SESSION_SECRET; then put_secret PREVIEW_SESSION_SECRET "$(gen 48)"; fi
if want_secret PREVIEW_JOBS_SECRET; then put_secret PREVIEW_JOBS_SECRET "$(gen 48)"; fi
if want_secret PREVIEW_ACCESS_TOKEN; then
  PREVIEW_ACCESS_TOKEN="$(gen 32)"
  put_secret PREVIEW_ACCESS_TOKEN "$PREVIEW_ACCESS_TOKEN"
  if to_clipboard "$PREVIEW_ACCESS_TOKEN"; then
    say "Токен входа в превью — в буфере обмена. Сохраните его в менеджере паролей."
    note "Ссылка превью: <адрес превью>/api/access/<этот токен>. В журналах она не печатается."
    pause "Сохранили? Enter —"
  fi
  PREVIEW_ACCESS_TOKEN=""
fi
if confirm "Включить настоящие пуш-уведомления в превью (необязательно)?"; then
  PREVIEW_VAPID="$(cd backend && uv run python -m app.push_keys 2>/dev/null | sed -n 's/^ORBITA_VAPID_PRIVATE_KEY=//p')"
  put_secret PREVIEW_VAPID_PRIVATE_KEY "$PREVIEW_VAPID"
  PREVIEW_VAPID=""
fi
pause "Enter — к окружению production"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Окружение production"
say "Ключи рабочей базы живут в отдельном окружении: прогоны на ветках их не видят."
gh api -X PUT "repos/$REPO/environments/$ENVIRONMENT" >/dev/null 2>&1 \
  && say "✓ окружение $ENVIRONMENT есть" || warn "не удалось создать окружение — создайте вручную: Settings → Environments"
put_secret PRODUCTION_DATABASE_URL "$PRODUCTION_DATABASE_URL" "$ENVIRONMENT"
want_secret PRODUCTION_URL "$ENVIRONMENT" && put_secret PRODUCTION_URL "$PRODUCTION_URL" "$ENVIRONMENT"
want_secret PRODUCTION_API_ORIGIN "$ENVIRONMENT" && put_secret PRODUCTION_API_ORIGIN "$PRODUCTION_API_ORIGIN" "$ENVIRONMENT"
# Секреты сессии и расписания обязаны совпадать в GitHub и Vercel: по секрету сессии выкладка
# выпускает первую ссылку, по секрету расписания GitHub будит API. Поэтому — пара, сразу в оба места.
if want_secret PRODUCTION_SESSION_SECRET "$ENVIRONMENT"; then
  PRODUCTION_SESSION_SECRET="$(gen 48)"
  put_secret PRODUCTION_SESSION_SECRET "$PRODUCTION_SESSION_SECRET" "$ENVIRONMENT"
else
  warn "секрет сессии не меняется — в Vercel оставляем прежний ORBITA_SESSION_SECRET"
fi
if want_secret PRODUCTION_JOBS_SECRET "$ENVIRONMENT"; then
  PRODUCTION_JOBS_SECRET="$(gen 48)"
  put_secret PRODUCTION_JOBS_SECRET "$PRODUCTION_JOBS_SECRET" "$ENVIRONMENT"
else
  warn "секрет расписания не меняется — в Vercel оставляем прежний ORBITA_JOBS_SECRET"
fi
if want_secret PRODUCTION_FIRST_ACCESS_TOKEN "$ENVIRONMENT"; then
  FIRST_TOKEN="$(gen 32)"
  put_secret PRODUCTION_FIRST_ACCESS_TOKEN "$FIRST_TOKEN" "$ENVIRONMENT"
  if to_clipboard "$FIRST_TOKEN"; then
    say "Токен первого входа — в буфере обмена. Сохраните его в менеджере паролей."
    note "Первый вход после выкладки: $PRODUCTION_URL/api/access/<этот токен> (SETUP, шаг 5)."
    pause "Сохранили? Enter —"
  fi
  FIRST_TOKEN=""
fi
pause "Enter — к переменным Vercel"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Переменные Vercel (окружение Production)"
say "Их читает работающий API; выкладка забирает их командой vercel pull."
[[ -n "$PRODUCTION_DATABASE_URL" ]] || ask_secret PRODUCTION_DATABASE_URL "Строка подключения production для Vercel (не отображается):"
[[ -n "$VERCEL_TOKEN" ]] || ask_secret VERCEL_TOKEN "Токен Vercel (не отображается):"
vercel_env ORBITA_ENV "production"
vercel_env ORBITA_TIMEZONE "Asia/Tashkent"
vercel_env ORBITA_BASE_URL "$PRODUCTION_URL"
vercel_env ORBITA_DATABASE_URL "$PRODUCTION_DATABASE_URL"
[[ -n "$PRODUCTION_SESSION_SECRET" ]] && vercel_env ORBITA_SESSION_SECRET "$PRODUCTION_SESSION_SECRET"
[[ -n "$PRODUCTION_JOBS_SECRET" ]] && vercel_env ORBITA_JOBS_SECRET "$PRODUCTION_JOBS_SECRET"
if confirm "Завести ключ уведомлений (утренняя сводка на iPhone)?"; then
  VAPID="$(cd backend && uv run python -m app.push_keys 2>/dev/null | sed -n 's/^ORBITA_VAPID_PRIVATE_KEY=//p')"
  if [[ -n "$VAPID" ]]; then vercel_env ORBITA_VAPID_PRIVATE_KEY "$VAPID"
  else warn "ключ не сгенерировался — нужна команда uv; позже: cd backend && uv run python -m app.push_keys"; fi
  VAPID=""
fi
PRODUCTION_DATABASE_URL=""; PRODUCTION_SESSION_SECRET=""; PRODUCTION_JOBS_SECRET=""
pause "Enter — к проверке"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Правила main и проверка"
if confirm "Включить защиту ветки main (только через PR с зелёными проверками)?"; then
  if gh api -X POST "repos/$REPO/rulesets" --input .github/rulesets/main.json >/dev/null 2>&1; then
    say "✓ защита main включена"
  else
    warn "не получилось (возможно, правило уже есть) — проверьте Settings → Rules → Rulesets"
  fi
fi
say "Секреты репозитория (только имена):"
gh secret list --repo "$REPO" --json name -q '.[].name' 2>/dev/null | sed 's/^/    /'
say "Секреты окружения $ENVIRONMENT (только имена):"
gh secret list --repo "$REPO" --env "$ENVIRONMENT" --json name -q '.[].name' 2>/dev/null | sed 's/^/    /'
# «Копию базы» здесь не предлагаем: до первой выкладки схема пуста, проверка снимка
# (таблиц больше нуля) падает и открывает задачу о несделанной копии — SETUP, шаг 4.
note "Дальше — первая выкладка: Actions → «Выкладка» → deploy, миграции — да."
note "Когда она пройдёт — Actions → «Копия базы» → Run workflow: снимок и число таблиц."
pause "Enter — итог"

finish
